### ISSUE TITLE
php composer.phar install 失败

### ISSUE THREAD

**Issue by ChenZeFengHi** [JadeVane/ssrpanel#1]
![image](https://user-images.githubusercontent.com/20348442/71240551-648e0a00-2344-11ea-8803-2482282156cb.png)

**Comment by ChenZeFengHi** [comment]
找到问题了，因为镜像失效问题导致的
https://github.com/ssrpanel/SSRPanel/issues/754
，大佬 你项目里貌似少了.env.example文件

**Comment by hu19940121** [comment]
> 找到问题了，因为镜像失效问题导致的
> [ssrpanel/SSRPanel#754](https://github.com/ssrpanel/SSRPanel/issues/754)
> ，大佬 你项目里貌似少了.env.example文件

你好 我也遇到了这个问题 请问你解决了吗

**Comment by ChenZeFengHi** [comment]
> > 找到问题了，因为镜像失效问题导致的
> > [ssrpanel/SSRPanel#754](https://github.com/ssrpanel/SSRPanel/issues/754)
> > ，大佬 你项目里貌似少了.env.example文件
> 
> 你好 我也遇到了这个问题 请问你解决了吗

如果是下载失败的话，看一下 https://github.com/ssrpanel/SSRPanel/issues/754

**Comment by JadeVane** [comment]
.env.example文件已添加
